const PRIMARY_COLOR = '#fdaa4f'

export default {
  BACKGROUND: '#040f0f',
  BACKGROUND_LIGHTER: '#2d3a3a',

  PRIMARY_COLOR,

  TAB_NAVIGATION: '#0D0E0F',

  BUTTON_DEFAULT: '#17181b',
  BUTTON_PRIMARY: '#212121',

  TEXT_COLOR: '#fcfffc',
  ICON_COLOR: '#fcfffc',
  ICON_ACTIVE: PRIMARY_COLOR,

  ITEM_ACTIVE_TAB_INDICATOR: PRIMARY_COLOR,
  ITEM_DROPDOWN_BACKGROUND: '#212121',
}
